name: Tests
on:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: testing
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm

      - run: npm ci
      # - run: npm run lint
      - run: npm test
